name: flash_card
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  # Hive
  hive: ^2.2.3
  build_runner: ^2.4.9
  hive_flutter: ^1.1.0
  hive_generator: ^1.0.0

  # Firebase
  firebase_remote_config: ^4.3.17
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_analytics: any
  firebase_messaging: 14.9.4
  flutter_local_notifications: ^16.3.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.7

  # logger
  logger: ^1.1.0

  #permission
  permission_handler: ^11.3.1


  # images animation
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/